---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls", "mysqls/status"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["services", "persistentvolumeclaims", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-rb
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-operator-role
  apiGroup: rbac.authorization.k8s.io