apiVersion: v2
name: myapp-chart
description: Helm-чарт для приложения myapp
type: application
version: 0.1.0
appVersion: "1.23.4"

dependencies:
- name: redis
  version: "18.0.0" # Рекомендуется указать конкретную стабильную версию
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled