apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-exporter
  labels:
    app: nginx-with-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-exporter
  template:
    metadata:
      labels:
        app: nginx-with-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   '/metrics'
        prometheus.io/port:   '9113'
    spec:
      containers:
      - name: nginx-with-exporter
        image: my-nginx-with-metrics:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 9113

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-svc
  labels:
    app: nginx-metrics
spec:
  type: ClusterIP
  selector:
    app: nginx-metrics
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113