---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: homework
spec:
  storageClassName: storage-class-homework
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi