---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
secrets:
  - name: monitoring-secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
secrets:
  - name: cd-secrets
