---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: monitoring
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Secret
metadata:
  name: cd-secrets
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token