---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-homework
  namespace: homework
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {
        "apiVersion": "storage.k8s.io/v1",
        "kind": "StorageClass",
        "metadata": {
            "annotations": {},
            "name": "cluster-storage"
        },
        "provisioner": "kubernetes.io/no-provisioner",
        "volumeBindingMode": "WaitForFirstConsumer"
      }
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain