apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-chart.fullname" . }}-config
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.appConfig | nindent 2 }}