{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "myapp-chart.fullname" . }}-default-deny
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "myapp-chart.fullname" . }}-allow-dns-and-redis
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  {{- if .Values.redis.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 6379
  {{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "myapp-chart.fullname" . }}-allow-from-ingress
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressControllerNamespace }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
{{- end }}
{{- end }}