{{- if .Values.appSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp-chart.fullname" . }}-secret
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.appSecrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}