---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homework
  namespace: homework
spec:
  storageClassName: storage-class-homework
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/homework